// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioBackend.Data;

#nullable disable

namespace PortfolioBackend.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20250411093406_UpdateProjects")]
    partial class UpdateProjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("PortfolioBackend.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompletedDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LiveDemoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnologiesUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedDate = "Not finished yet",
                            Description = "A personal portfolio website showcasing my development projects and skills",
                            GitHubUrl = "https://github.com/SiebeKeuppens/Portfolio",
                            ImageUrl = "/assets/images/portfolio.png",
                            IsFeatured = false,
                            LiveDemoUrl = "#",
                            TechnologiesUsed = "Angular, TypeScript, JaveScript, C#, .NET Core, Entity Framework Core, SQLite",
                            Title = "Portfolio Website"
                        },
                        new
                        {
                            Id = 2,
                            CompletedDate = "07-00-YYYY",
                            Description = "A Virtual Reality game about Portals",
                            GitHubUrl = "https://github.com/NicolaiDG/ImmersiveProjectV3",
                            ImageUrl = "/assets/images/hubpreview.png",
                            IsFeatured = true,
                            LiveDemoUrl = "https://sidequestvr.com/app/40113/enter-the-world-of-geology",
                            TechnologiesUsed = "Unity, C#, Entity Framework Core, SQLite",
                            Title = "Immersive Storytelling"
                        },
                        new
                        {
                            Id = 3,
                            CompletedDate = "11-34-YYYY",
                            Description = "A personal portfolio website showcasing my development projects and skills",
                            GitHubUrl = "unkown",
                            ImageUrl = "/assets/images/portfolio.jpg",
                            IsFeatured = true,
                            LiveDemoUrl = "unknown",
                            TechnologiesUsed = "Angular, .NET Core, Entity Framework Core, SQLite",
                            Title = "Portfolio Website"
                        },
                        new
                        {
                            Id = 4,
                            CompletedDate = "11-34-YYYY",
                            Description = "A personal portfolio website showcasing my development projects and skills",
                            GitHubUrl = "unkown",
                            ImageUrl = "/assets/images/portfolio.jpg",
                            IsFeatured = true,
                            LiveDemoUrl = "unknown",
                            TechnologiesUsed = "Angular, .NET Core, Entity Framework Core, SQLite",
                            Title = "Portfolio Website"
                        },
                        new
                        {
                            Id = 5,
                            CompletedDate = "11-34-YYYY",
                            Description = "A personal portfolio website showcasing my development projects and skills",
                            GitHubUrl = "unkown",
                            ImageUrl = "/assets/images/portfolio.jpg",
                            IsFeatured = false,
                            LiveDemoUrl = "unknown",
                            TechnologiesUsed = "Angular, .NET Core, Entity Framework Core, SQLite",
                            Title = "Portfolio Website"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
